"
" My vimrc file :>
"
set encoding=utf-8
set nocompatible              " be iMproved, required
filetype off                  " required

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'Valloric/YouCompleteMe'
Plug 'vim-scripts/Conque-GDB'
Plug 'kien/ctrlp.vim'
Plug 'tpope/vim-dispatch'
Plug 'SirVer/hltisnips'
Plug 'PotatoesMaster/i3-vim-syntax'

call plug#end()

set path+=**
set encoding=utf-8
scriptencoding utf-8

" Load powerline bindings
set rtp+=$powerline_path/bindings/vim

" Always show statusline
set laststatus=2

" Use 256 colours (Use this setting only if your terminal supports 256 colours)
set t_Co=256

set listchars=tab:⟶\ 
" Optional space list character
"space:·
set list

set number
set relativenumber
set nowrap

if has("vms")
    set nobackup      " do not keep a backup file, use versions instead
else
    set backup        " keep a backup file (restore to previous version)
    if has("persistent_undo")
        set undofile    " keep an undo file (undo changes after closing)
    endif
endif

" Only do this part when compiled with support for autocommands.
if has("autocmd")

    " Automatically apply key mappings
    autocmd VimEnter xmodmap ~/.Xmodmap

    " Put these in an autocmd group, so that we can delete them easily.
    augroup vimrcEx
    au!
    " For all text files set 'textwidth' to 78 characters.
    autocmd FileType text setlocal textwidth=78
    augroup END

    " Default settings for tab as 4 spaces
    set expandtab shiftwidth=4 tabstop=4
    " Setting for python files using tabs with 8 spaces
    autocmd Filetype python setlocal noexpandtab sw=4 ts=4 sts=4

else
    set autoindent        " always set autoindenting on
endif " has("autocmd")

" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
if has('syntax') && has('eval')
    packadd matchit
endif

" Build mappings
nnoremap <F5> :source ./.run.vim<CR>:ConqueGdbVSplit -d <C-R>=debug_cwd<CR> --args <C-R>=debug_cmd<CR><CR>
nnoremap <F7> :Dispatch<CR>

" Build file to run relative to project structure
set makeprg=./.makeprg

" Snippet hotkeys
let g:UltiSnipsExpandTrigger="<space>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

let g:ycm_confirm_extra_conf = 0
